### ISSUE TITLE
Enable the merge button only if the user is the pull-request assignee

### ISSUE THREAD

**Issue by utaal** [buildo/github-workflow-pal#21]
Migrated from https://github.com/buildo/infra/issues/134 by @ascariandrea .

I'm still trying to figure out if this could be helpful or not, but we can discuss.

It should be helpful for prevent accidental merges.
We can also disable it for the user that creates the pr, avoiding self-merging pr.
Obviously considering the project specs and workflow.

**Comment by FrancescoCioria** [comment]
I think the only effect this would have is to force the user who wants to merge it to self-assign the PR and then merge it :stuck_out_tongue_closed_eyes: 
IMO this extension should **help** us following some convention not force us (that's why you can still merge PRs without a test plan if you really want it)

@buildo/everyone

**Comment by gabro** [comment]
I would consider this in case we have issues with accidental merges, but this doesn't seem the case, so far. I'd skip it for now.

**Comment by FrancescoCioria** [comment]
> I would consider this in case we have issues with accidental merges

I think we can always revert merges in the event of a wrong merge

**Comment by gabro** [comment]
Yup. Not the best scenario ever, but yes. Anyway, closing until we have a concrete use case.
